### ISSUE TITLE
The settings page is not available.

### ISSUE THREAD

**Issue by netchild** [aussig/BGS-Tally#258]
**Describe the bug**
![BGS-tally-in-EDMC](https://github.com/aussig/BGS-Tally/assets/3617760/1d7f39fc-8643-4d35-b346-fd21cde8312a)
As you can see, BGS Talyy 4.0 is installed (updated from 3.x).

![EDMC-Settings](https://github.com/aussig/BGS-Tally/assets/3617760/5ed19534-d4fe-4844-a5f5-dea7894fa559)
But there is no settings page for it.

Windows 11, most recent EDMC (updated yesterday), German desktop language.

**Comment by aussig** [comment]
You havent filled in the full bug report - I’ll need your log files attached please.

**Comment by netchild** [comment]
Seems there is an hardcoded path?

2024-06-08 10:59:10.852 UTC - ERROR - 12960:24804:24804 plug.Plugin.get_prefs:151: Failed for Plugin "BGS-Tally"
Traceback (most recent call last):
  File "plug.pyc", line 146, in get_prefs
  File "C:\Users\Alexa\AppData\Local\EDMarketConnector\plugins\BGS-Tally-3.1.0\load.py", line 47, in plugin_prefs
    return this.ui.get_prefs_frame(parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alexa\AppData\Local\EDMarketConnector\plugins\BGS-Tally-3.1.0\bgstally\ui.py", line 170, in get_prefs_frame
    self.languages: dict[str: str] = available_langs()
                                     ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alexa\AppData\Local\EDMarketConnector\plugins\BGS-Tally-3.1.0\bgstally\utils.py", line 52, in available_langs
    available:set[str] = {x[:-len('.strings')] for x in listdir(plugin_path)
                                                        ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Alexa\\AppData\\Local\\EDMarketConnector\\**plugins\\BGS-Tally\\L10n'**

**Comment by netchild** [comment]
Yes, renaming the plugin to something without a version number makes the settings screen appear.

**Comment by aussig** [comment]
Good find. I’ll take a look at this as soon as I can.
