### ISSUE TITLE
BGS-Tally fails to load

### ISSUE THREAD

**Issue by MarcusHu29** [aussig/BGS-Tally#63]
**Describe the bug**
The tick.py module seems to have a parsing problem with the time format and stops the plugin from loading.

**To Reproduce**
1. Start EDMC - Plugin not recognized and not displayed.

**Expected behavior**
Should show some Information on BGS work and in the EDMC settings there should be a BGS-Tally tab which isn't.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Plugin Version 2.0.1
 - EDMC Version 5.5.0

**Additional context**
EDMC log here:

2022-10-25 19:07:53.480 UTC - INFO - 29644:31852:31852 EDMarketConnector.__main__:1868: Startup v5.5.0+2fba41c : Running on Python v3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 13:51:36) [MSC v.1933 32 bit (Intel)]
E:D Market Connector 5.5.0+2fba41c
2022-10-25 19:07:53.512 UTC - INFO - 29644:31852:31852 killswitch.fetch_kill_switches:341: Attempting to fetch kill switches
2022-10-25 19:08:00.330 UTC - INFO - 29644:31852:31852 killswitch.parse_kill_switches:404: Kill switches last updated 18 October 2021
2022-10-25 19:08:00.452 UTC - INFO - 29644:31852:31852 plug.Plugin.__init__:47: loading plugin "coriolis" from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
2022-10-25 19:08:00.473 UTC - INFO - 29644:31852:31852 plug.Plugin.__init__:47: loading plugin "eddb" from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
2022-10-25 19:08:00.476 UTC - INFO - 29644:31852:31852 plug.Plugin.__init__:47: loading plugin "eddn" from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
2022-10-25 19:08:00.480 UTC - INFO - 29644:31852:31852 plug.Plugin.__init__:47: loading plugin "edsm" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
2022-10-25 19:08:00.486 UTC - INFO - 29644:31852:31852 plug.Plugin.__init__:47: loading plugin "edsy" from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
2022-10-25 19:08:00.488 UTC - INFO - 29644:31852:31852 plug.Plugin.__init__:47: loading plugin "inara" from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
2022-10-25 19:08:00.496 UTC - INFO - 29644:31852:31852 plug.Plugin.__init__:47: loading plugin "BGS-Tally" from "C:\Users\Marcus\AppData\Local\EDMarketConnector\plugins\BGS-Tally\load.py"
2022-10-25 19:08:00.503 UTC - ERROR - 29644:31852:31852 plug.Plugin.__init__:62: : Failed for Plugin "BGS-Tally"
Traceback (most recent call last):
  File "plug.pyc", line 53, in __init__
  File "C:\Users\Marcus\AppData\Local\EDMarketConnector\plugins\BGS-Tally\load.py", line 16, in plugin_start3
    this.plugin_start(plugin_dir)
  File "C:\Users\Marcus\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\bgstally.py", line 45, in plugin_start
    self.tick: Tick = Tick(self, True)
  File "C:\Users\Marcus\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\tick.py", line 24, in __init__
    if load: self.load()
  File "C:\Users\Marcus\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\tick.py", line 64, in load
    self.tick_time = datetime.strptime(config.get_str("XTickTime"), DATETIME_FORMAT_ELITEBGS)
TypeError: strptime() argument 1 must be str, not None
2022-10-25 19:08:00.509 UTC - ERROR - 29644:31852:31852 plug.load_plugins:159: Failure loading found Plugin "BGS-Tally"
Traceback (most recent call last):
  File "plug.pyc", line 157, in load_plugins
  File "plug.pyc", line 53, in __init__
  File "C:\Users\Marcus\AppData\Local\EDMarketConnector\plugins\BGS-Tally\load.py", line 16, in plugin_start3
    this.plugin_start(plugin_dir)
  File "C:\Users\Marcus\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\bgstally.py", line 45, in plugin_start
    self.tick: Tick = Tick(self, True)
  File "C:\Users\Marcus\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\tick.py", line 24, in __init__
    if load: self.load()
  File "C:\Users\Marcus\AppData\Local\EDMarketConnector\plugins\BGS-Tally\bgstally\tick.py", line 64, in load
    self.tick_time = datetime.strptime(config.get_str("XTickTime"), DATETIME_FORMAT_ELITEBGS)
TypeError: strptime() argument 1 must be str, not None
2022-10-25 19:08:00.595 UTC - INFO - 29644:31852:31852 monitor.EDLogs.start:255: Monitoring Journal Folder: "C:\Users\Marcus\Saved Games\Frontier Developments\Elite Dangerous"
2022-10-25 19:08:00.596 UTC - INFO - 29644:31852:31852 monitor.EDLogs.start:256: Start Journal File: "C:\Users\Marcus\Saved Games\Frontier Developments\Elite Dangerous\Journal.2022-10-25T205924.01.log"
2022-10-25 19:08:03.912 UTC - INFO - 29644:31852:31852 EDMarketConnector.AppWindow.journal_event:1369: Startup or LoadGame event
2022-10-25 19:08:03.919 UTC - INFO - 29644:31852:31852 dashboard.Dashboard.start:92: Monitoring Dashboard "C:\Users\Marcus\Saved Games\Frontier Developments\Elite Dangerous"
2022-10-25 19:08:35.507 UTC - INFO - 29644:31748:31748 plugins.inara.new_worker:1540: sending 4 events for Molly Armitage
2022-10-25 19:36:03.858 UTC - INFO - 29644:31852:31852 EDMarketConnector.AppWindow.HelpAbout.__init__:1639: Current version is 5.5.0+2fba41c

**Comment by aussig** [comment]
@MarcusHu29 Would you be happy testing a change to fix this?

If so, grab [this version of state.py](https://raw.githubusercontent.com/aussig/BGS-Tally/develop/bgstally/state.py) and [this version of tick.py](https://raw.githubusercontent.com/aussig/BGS-Tally/develop/bgstally/tick.py) and put them into your `BGS-Tally/bgstally/` folder, replacing the existing versions.

**Comment by MarcusHu29** [comment]
Yep. Those 2 versions did the trick! It's working now!
